### ISSUE TITLE
Install with composer

### ISSUE THREAD

**Issue by Seb33300** [ThomasKeil/pimcore-plugin-DynamicDropdown#10]
Hi,

Since august 2014, pimcore extension hub is no longer supported to the benefit of composer.
https://www.pimcore.org/en/resources/blog/extension+management+using+composer_b522?page=2

In order to make your plugin installable with composer, it needs to have a composer.json file.
Can you consider adding one?

You can found an example on the official pimcore example plugin:
https://github.com/pimcore/plugin-example

Regards
Seb

**Comment by ThomasKeil** [comment]
Hi,


Am 26.01.2015 um 14:39 schrieb Sébastien ALFAIATE:
> In order to make your plugin installable with composer, it needs to
> have a composer.json file.
>
> Can you consider adding one?
>
>
Yes - a complete rework of the plugin is already in the works!

Please have a little patience :-)


Cheers
Thomas

**Comment by Seb33300** [comment]
Hi,

When will you plan to publish it?
In few days/weeks/month?

We are upgrading an existing app, we can't wait more than few days.
So we will need to fork your plugin if you could not add a composer.json

Seb

**Comment by ThomasKeil** [comment]
Am 26.01.2015 um 16:40 schrieb Sébastien ALFAIATE:
>
> Hi,
>
> When will you plan to publish it?
> In few days/weeks/month?
>
> We are upgrading an existing app, we can't wait more than few days.
> So we will need to fork your plugin if you could not add a composer.json
>
Check this out:

https://packagist.org/packages/weblizards-gmbh/dynamicdropdown-plugin


Untested!!

Can you confirm that this is (not?) working?

Cheers
Thomas

**Comment by ThomasKeil** [comment]
Am 2015-01-26 16:40, schrieb Sébastien ALFAIATE:
> Hi,
>
> When will you plan to publish it?
>  In few days/weeks/month?
Okay, there are still a few issues with Composer - I'm on it,  these 
are just some minor things.

I think this will be done within this week =)

Cheers
Thomas

**Comment by Seb33300** [comment]
Hi.

I juste tested to install with composer.
I get this error:

> require_once(/var/www/plugins/DynamicDropdown/lib/DynamicDropdown/Plugin.php): failed to open stream: No such file or directory /var/www/pimcore/lib/Zend/Loader/ClassMapAutoloader.php 148 Array

Plugin folder name is not correct.
Composer installed it in /plugins/DynamicDropdownPlugin/

Thanks for your work

**Comment by ThomasKeil** [comment]
Correction of these Errors are in  the works - please be patient :)

**Comment by Seb33300** [comment]
Hi,

Just see you have updated it yesterday to make it working with composer.

You seems to have forgot to change the css path:
```
<pluginCssPaths>
        <path>/Dynamicdropdown/static/css/admin.css</path>
</pluginCssPaths>
```

**Comment by Seb33300** [comment]
I tried to use it on a project with the old version.

I can install it side by side with the old plugin.
If I disable the old plugin, this is working, but when I delete the old plugin, i can't see my object in the pimcore tree.

Don't know why, no error is displaying :/

**Comment by ThomasKeil** [comment]
Hi,

Am 29.01.2015 um 11:01 schrieb Sébastien ALFAIATE:
> Just see you have updated it yesterday to make it working with composer. 
Yes, I'm working on it...

> You seems to have forgot to change the css path:
>
> |<pluginCssPaths>
>         <path>/Dynamicdropdown/static/css/admin.css</path>
> </pluginCssPaths>|
That's right - thanks!

I'll update that this evening.

Thomas

**Comment by Seb33300** [comment]
Thanks!

I tried to use it on a project with the old version.

I can install it side by side with the old plugin.
If I disable the old plugin, this is working, but when I delete the old plugin, i can't see my object in the pimcore tree.

Don't know why, no error is displaying :/

**Comment by Seb33300** [comment]
Do you still working on it?

I still can't use your new plugin after installing it with composer.

> Fatal error:  require_once(): Cannot redeclare class zend_loader_pluginloader_interface in /var/www/sa.dev.pimcore.duodisplay.galilee.fr/pimcore/lib/Zend/Loader/ClassMapAutoloader.php on line 148

**Comment by Seb33300** [comment]
OK just found the issue, we need to regererate classmap to make it working.
pimcore/cli/classmap_generator.php

Thanks!

**Comment by ThomasKeil** [comment]
Am 02.02.2015 um 10:36 schrieb Sébastien ALFAIATE:
>
> OK just found the issue, we need to regererate classmap to make it
> working.
> pimcore/cli/classmap_generator.php
>
>
Is there a way to trigger that with composer?

**Comment by Seb33300** [comment]
I don't think so.

Maybe this happen because you are using the old namespace syntax in some of pour classes.
Its seems that classmap must be regenerated when using the old namspace syntax in pimcore 3 project.

**Comment by ThomasKeil** [comment]
Am 02.02.2015 um 11:13 schrieb Sébastien ALFAIATE:
>
> I don't think so.
>
> Maybe this happen because you are using the old namespace syntax in
> some of pour classes.
> Its seems that classmap must be regenerated when using the old
> namspace syntax in pimcore 3 project.
>
>
I'll check that.

**Comment by mediafant** [comment]
Vielen Dank für Ihre Nachricht. Ich bin derzeit nicht im Büro und werde mich so bald als möglich mit Ihnen in Verbindung setzen.

In dringenden Fällen wenden Sie sich bitte an meine Kollegin Muriel Luzot:
 muriel.luzot@gmx.net

Schöne Grüße
Andreas Wulf
