### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by Techsigns** [ThomasKeil/pimcore-plugin-DynamicDropdown#14]
I've just updated from Pimcore 3.1.1 to 4.3.1 and also updated the DynamicDropdown-Plugin to current version for Pimcore 4. Everything seems fine except the autocompletion does not work (ExtJS 6, new interface). When typing a text into the field the field gets blank. When drop down is open the cursor jumps to the top position

**Comment by ThomasKeil** [comment]
I just commited some fixes - could you please check if it now works as expected?

**Comment by Techsigns** [comment]
No, it doesn't work. Same bug as before

**Comment by Techsigns** [comment]
Please see attached video, hope this makes it more clearer :)

[bug-pimcore-dynamicdropdown.zip](https://github.com/ThomasKeil/pimcore-plugin-DynamicDropdown/files/581465/bug-pimcore-dynamicdropdown.zip)

**Comment by ThomasKeil** [comment]
Thanks for the video!

I can see the issue, and can reproduce it - but currently I have no idea how to fix it.
Please be a little patient...

**Comment by Techsigns** [comment]
Maybe you can have a look at the Pimcore module for the country selection. I think it is similar, regarding the ExtJS6 component

**Comment by ThomasKeil** [comment]
@Techsigns 
I think I found the reason for that, the "mode" parameter for comboboxes got renamed to "queryMode", thus the combobox reload the whole time.
Setting it to "queryMode" should fix this issue - can you confirm that?

**Comment by Techsigns** [comment]
I've just tested the fix and can confirm that the autocomplete now works as expected! Thank you very much

**Comment by ThomasKeil** [comment]
Great, thanks for your feedback.
