### ISSUE TITLE
Grid display broken for Dynamic Dropdown (select)

### ISSUE THREAD

**Issue by Yivan** [ThomasKeil/pimcore-plugin-DynamicDropdown#17]
In the grid listing, the Dynamic Dropdown (select) break the grid (field after are empty) and itselft it doesn't print the data too.

Here is a screenshot:
![1](https://cloud.githubusercontent.com/assets/9025839/20506669/d392d30a-b055-11e6-9859-09c965aec97a.png)

If myselect (Dynamic Dropdown (select)) is not displayed, next field work ok:
![2](https://cloud.githubusercontent.com/assets/9025839/20506684/e97d7792-b055-11e6-9483-5d9fe19bc29c.png)

**Comment by ThomasKeil** [comment]
I just added support for gridmode for the single dropdown input. It works for me - can you please check if it fixes ýour problem?

**Comment by Yivan** [comment]
Thanks Thomas, it works fine now!

**Comment by ThomasKeil** [comment]
Great - thanks for your feedback.
