### ISSUE TITLE
Cache need to be emptied to see tree changes

### ISSUE THREAD

**Issue by Yivan** [ThomasKeil/pimcore-plugin-DynamicDropdown#18]
If you add new objects on the object tree, the 4 dropdowns element type don't use the new objects as select choice.
If the cache is cleared, those new objects are available in the dropdowns on the object edit panel.

So this issue is about new object in the tree. They should be available as a dropdown option as soon as the object is added, without having to clear the cache.

**Comment by ThomasKeil** [comment]
I added some tagging to the cacheing, this should fix this issue.
Can you verify that?

**Comment by Yivan** [comment]
Just tryed it, but I got always the problem. I added an object to the tree, but i need to clear the cache to view it on the object panel edit having dropdown.

I checked your new code and see it handle tags for directory too. So I made some further test:
- saving the folder containing the objects flush the cache: ok
- saving an existing object flush the cache: ok

But problem here is adding a new object in the folder don't flush the cache (tagging cannot work as it is a new object). I think it should be thinked for adding object in subfolders too (related to the recursive option of the dropdown element in class editor).

**Comment by ThomasKeil** [comment]
Thanks for testing this.
Weird that adding an item to a folder doesn't trigger flushing the cache of the involved items. I'll have to think of something else...

**Comment by Yivan** [comment]
Maybe we could remove the cache functionnality ? Is it really necessary, as when we got more than 100 for instance, the dropdown would not be very usable and Pimcore native href will be more easy for enduser.

**Comment by ThomasKeil** [comment]
I just removed the functionality as suggested - the performance improvement is not worth the effort.

Thanks for your feedback!
Thomas

**Comment by Yivan** [comment]
Thanks, i confirm it works great now!
