### ISSUE TITLE
Improve Pimcore 4 compatibility use JSON instead PSF

### ISSUE THREAD

**Issue by Yivan** [ThomasKeil/pimcore-plugin-DynamicDropdown#20]
It seems some code rely on PSF, as it can be seen here:
https://github.com/ThomasKeil/pimcore-plugin-DynamicDropdown/blob/0b9f39bc22b6f6fb385b1aaa15b3237637cfcc51/controllers/DynamicdropdownController.php#L177

Pimcore save definition as JSON now, so maybe this part of code don't work no more and need to be rewriten.

I hope it make sense and will improve stablity of this great plugin.
Thanks a lot.

**Comment by ThomasKeil** [comment]
The current release now uses the PHP definition files instead of the psf files.

**Comment by Yivan** [comment]
Thanks again!
