### ISSUE TITLE
Improvement: add autocomplete to the combobox (superboxselect)

### ISSUE THREAD

**Issue by Yivan** [ThomasKeil/pimcore-plugin-DynamicDropdown#22]
Ext offer the possibility to add an autocompletion to select element. This could be great in the case of the superboxselect. If there are many element to choose from, the enduser could use this to refine the selected tag possibility. It would make the superboxselect a very distincitive usage from classic select (dropdown or native pimcore) as it could handle easily long list of select option.

You can see the typeAhea feature here http://docs.sencha.com/extjs/6.0.1/classic/Ext.form.field.Tag.html#cfg-typeAhead.
It should be easy to implement (just small js change in https://github.com/ThomasKeil/pimcore-plugin-DynamicDropdown/blob/master/static6/js/DynamicDropdown/tags/superboxselect.js) and so great : )

Thanks.

**Comment by Yivan** [comment]
I made some test, and adding
```
typeAhead: true,
queryMode: "local",
```
below https://github.com/ThomasKeil/pimcore-plugin-DynamicDropdown/blob/master/static6/js/DynamicDropdown/tags/superboxselect.js#L49 seems to work great!

**Comment by ThomasKeil** [comment]
I just added those options - please test!

**Comment by Yivan** [comment]
Sorry for the time i take to come back.
Thanks a lot Thomas I confirm it works fine! The issue can be closed.

**Comment by ThomasKeil** [comment]
No Problem, thanks for your feedback!
